name: nCore
version: 2.0
main: pl.nelson.ncore.Main
api-version: '1.21'
author: Nelson

commands:
  setspawn:
    description: Define el punto de spawn global.
    permission: ncore.admin
  spawn:
    description: Te lleva al spawn del servidor.
    usage: /spawn
  regresar:
    description: Te devuelve a la ubicación donde te desconectaste.
  rtp:
    description: Teletransportarse a un lugar aleatorio.
  cofre:
    description: Te teletransporta a tu cofre de muerte activo.
    usage: /cofre

permissions:
  ncore.admin:
    description: Acceso a comandos de administración y ver cofres ajenos.
    default: op
